# Generated by Django 3.0.7 on 2020-08-19 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_auto_20200819_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
